
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 27 2025 11:57:42 IST (Aug 27 2025 06:27:42 UTC)

// Verification Directory fv/Traffic_controller 

module RC_CG_MOD(enable, ck_in, ck_out, test);
  input enable, ck_in, test;
  output ck_out;
  wire enable, ck_in, test;
  wire ck_out;
  TLATNTSCAX2 RC_CGIC_INST(.E (enable), .CK (ck_in), .SE (test), .ECK
       (ck_out));
endmodule

module Traffic_controller(clk, rst, NS, EW);
  input clk, rst;
  output [1:0] NS, EW;
  wire clk, rst;
  wire [1:0] NS, EW;
  wire [1:0] state;
  wire [31:0] timer;
  wire dec_sub_41_18_n_306, dec_sub_41_18_n_311, dec_sub_41_18_n_316,
       dec_sub_41_18_n_321, dec_sub_41_18_n_326, dec_sub_41_18_n_331,
       dec_sub_41_18_n_336, dec_sub_41_18_n_341;
  wire dec_sub_41_18_n_346, dec_sub_41_18_n_351, dec_sub_41_18_n_356,
       dec_sub_41_18_n_361, dec_sub_41_18_n_366, dec_sub_41_18_n_371,
       dec_sub_41_18_n_376, dec_sub_41_18_n_381;
  wire dec_sub_41_18_n_386, dec_sub_41_18_n_391, dec_sub_41_18_n_396,
       dec_sub_41_18_n_401, dec_sub_41_18_n_406, dec_sub_41_18_n_411,
       dec_sub_41_18_n_416, dec_sub_41_18_n_421;
  wire dec_sub_41_18_n_426, dec_sub_41_18_n_431, dec_sub_41_18_n_436,
       dec_sub_41_18_n_441, dec_sub_41_18_n_446, dec_sub_41_18_n_451,
       n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, rc_gclk;
  RC_CG_MOD RC_CG_HIER_INST0(.enable (n_46), .ck_in (clk), .ck_out
       (rc_gclk), .test (1'b0));
  OR2X1 g1035__2398(.A (state[0]), .B (n_78), .Y (n_46));
  OR4X1 g1036__5107(.A (timer[26]), .B (n_43), .C (n_42), .D (n_45), .Y
       (n_78));
  OR4X1 g1037__6260(.A (timer[7]), .B (timer[27]), .C (n_41), .D
       (n_44), .Y (n_45));
  NAND4BXL g1038__4319(.AN (timer[6]), .B (n_36), .C (n_37), .D (n_39),
       .Y (n_44));
  OR4X1 g1039__8428(.A (timer[4]), .B (timer[29]), .C (timer[1]), .D
       (n_38), .Y (n_43));
  OR4X1 g1040__5526(.A (timer[24]), .B (timer[25]), .C (timer[28]), .D
       (n_40), .Y (n_42));
  OR4X1 g1041__6783(.A (timer[5]), .B (timer[8]), .C (timer[16]), .D
       (timer[19]), .Y (n_41));
  OR4X1 g1042__3680(.A (timer[0]), .B (timer[21]), .C (timer[22]), .D
       (timer[23]), .Y (n_40));
  NOR4X1 g1043__1617(.A (timer[12]), .B (timer[11]), .C (timer[13]), .D
       (timer[14]), .Y (n_39));
  OR4X1 g1044__2802(.A (timer[2]), .B (timer[30]), .C (timer[3]), .D
       (timer[31]), .Y (n_38));
  NOR4X1 g1045__1705(.A (timer[20]), .B (timer[15]), .C (timer[17]), .D
       (timer[18]), .Y (n_37));
  AND2XL g1046__5122(.A (state[0]), .B (EW[1]), .Y (NS[0]));
  AND2XL g1047__8246(.A (state[0]), .B (NS[1]), .Y (EW[0]));
  NOR2XL g1048__7098(.A (timer[10]), .B (timer[9]), .Y (n_36));
  DFFRHQX1 \timer_reg[0] (.RN (rst), .CK (clk), .D (n_33), .Q
       (timer[0]));
  DFFRHQX1 \state_reg[0] (.RN (rst), .CK (clk), .D (n_34), .Q
       (state[0]));
  DFFRHQX1 \timer_reg[3] (.RN (rst), .CK (rc_gclk), .D (n_32), .Q
       (timer[3]));
  XNOR2X1 g843__6131(.A (NS[1]), .B (n_31), .Y (n_35));
  DFFRHQX1 \timer_reg[9] (.RN (rst), .CK (rc_gclk), .D (n_14), .Q
       (timer[9]));
  DFFRHQX1 \timer_reg[24] (.RN (rst), .CK (rc_gclk), .D (n_29), .Q
       (timer[24]));
  DFFRHQX1 \timer_reg[25] (.RN (rst), .CK (rc_gclk), .D (n_28), .Q
       (timer[25]));
  DFFRHQX1 \timer_reg[26] (.RN (rst), .CK (rc_gclk), .D (n_30), .Q
       (timer[26]));
  DFFRHQX1 \timer_reg[27] (.RN (rst), .CK (rc_gclk), .D (n_26), .Q
       (timer[27]));
  DFFRHQX1 \timer_reg[28] (.RN (rst), .CK (rc_gclk), .D (n_25), .Q
       (timer[28]));
  DFFRHQX1 \timer_reg[29] (.RN (rst), .CK (rc_gclk), .D (n_24), .Q
       (timer[29]));
  DFFRHQX1 \timer_reg[30] (.RN (rst), .CK (rc_gclk), .D (n_27), .Q
       (timer[30]));
  DFFRHQX1 \timer_reg[31] (.RN (rst), .CK (rc_gclk), .D (n_22), .Q
       (timer[31]));
  DFFRHQX1 \timer_reg[2] (.RN (rst), .CK (rc_gclk), .D (n_19), .Q
       (timer[2]));
  DFFRHQX1 \timer_reg[4] (.RN (rst), .CK (rc_gclk), .D (n_18), .Q
       (timer[4]));
  DFFRHQX1 \timer_reg[5] (.RN (rst), .CK (rc_gclk), .D (n_17), .Q
       (timer[5]));
  DFFRHQX1 \timer_reg[6] (.RN (rst), .CK (rc_gclk), .D (n_21), .Q
       (timer[6]));
  DFFRHQX1 \timer_reg[7] (.RN (rst), .CK (rc_gclk), .D (n_13), .Q
       (timer[7]));
  DFFRHQX1 \timer_reg[8] (.RN (rst), .CK (rc_gclk), .D (n_15), .Q
       (timer[8]));
  DFFRHQX1 \timer_reg[23] (.RN (rst), .CK (rc_gclk), .D (n_23), .Q
       (timer[23]));
  DFFRHQX1 \timer_reg[10] (.RN (rst), .CK (rc_gclk), .D (n_12), .Q
       (timer[10]));
  DFFRHQX1 \timer_reg[11] (.RN (rst), .CK (rc_gclk), .D (n_10), .Q
       (timer[11]));
  DFFRHQX1 \timer_reg[12] (.RN (rst), .CK (rc_gclk), .D (n_9), .Q
       (timer[12]));
  DFFRHQX1 \timer_reg[13] (.RN (rst), .CK (rc_gclk), .D (n_8), .Q
       (timer[13]));
  DFFRHQX1 \timer_reg[14] (.RN (rst), .CK (rc_gclk), .D (n_7), .Q
       (timer[14]));
  DFFRHQX1 \timer_reg[15] (.RN (rst), .CK (rc_gclk), .D (n_6), .Q
       (timer[15]));
  DFFRHQX1 \timer_reg[16] (.RN (rst), .CK (rc_gclk), .D (n_5), .Q
       (timer[16]));
  DFFRHQX1 \timer_reg[17] (.RN (rst), .CK (rc_gclk), .D (n_4), .Q
       (timer[17]));
  DFFRHQX1 \timer_reg[18] (.RN (rst), .CK (rc_gclk), .D (n_3), .Q
       (timer[18]));
  DFFRHQX1 \timer_reg[19] (.RN (rst), .CK (rc_gclk), .D (n_2), .Q
       (timer[19]));
  DFFRHQX1 \timer_reg[20] (.RN (rst), .CK (rc_gclk), .D (n_11), .Q
       (timer[20]));
  DFFRHQX1 \timer_reg[21] (.RN (rst), .CK (rc_gclk), .D (n_16), .Q
       (timer[21]));
  DFFRHQX1 \timer_reg[22] (.RN (rst), .CK (rc_gclk), .D (n_1), .Q
       (timer[22]));
  DFFRHQX1 \timer_reg[1] (.RN (rst), .CK (clk), .D (n_20), .Q
       (timer[1]));
  OAI2BB1X1 g874__1881(.A0N (state[0]), .A1N (n_78), .B0 (n_46), .Y
       (n_34));
  OAI21XL g875__5115(.A0 (timer[0]), .A1 (n_0), .B0 (n_46), .Y (n_33));
  OAI2BB1X1 g876__7482(.A0N (n_49), .A1N (n_78), .B0 (n_31), .Y (n_32));
  AND2X1 g877__4733(.A (n_72), .B (n_78), .Y (n_30));
  AND2X1 g878__6161(.A (n_70), .B (n_78), .Y (n_29));
  AND2X1 g879__9315(.A (n_71), .B (n_78), .Y (n_28));
  AND2X1 g880__9945(.A (n_76), .B (n_78), .Y (n_27));
  AND2X1 g881__2883(.A (n_73), .B (n_78), .Y (n_26));
  AND2X1 g882__2346(.A (n_74), .B (n_78), .Y (n_25));
  AND2X1 g883__1666(.A (n_75), .B (n_78), .Y (n_24));
  AND2X1 g884__7410(.A (n_69), .B (n_78), .Y (n_23));
  AND2X1 g885__6417(.A (n_77), .B (n_78), .Y (n_22));
  AND2X1 g886__5477(.A (n_78), .B (n_52), .Y (n_21));
  AND2X1 g888__2398(.A (n_78), .B (n_48), .Y (n_19));
  AND2X1 g889__5107(.A (n_78), .B (n_50), .Y (n_18));
  AND2X1 g890__6260(.A (n_78), .B (n_51), .Y (n_17));
  NAND2XL g891__4319(.A (state[0]), .B (n_0), .Y (n_31));
  AND2X1 g892__8428(.A (n_67), .B (n_78), .Y (n_16));
  AND2X1 g893__5526(.A (n_54), .B (n_78), .Y (n_15));
  AND2X1 g894__6783(.A (n_55), .B (n_78), .Y (n_14));
  AND2X1 g895__3680(.A (n_53), .B (n_78), .Y (n_13));
  AND2X1 g896__1617(.A (n_56), .B (n_78), .Y (n_12));
  AND2X1 g897__2802(.A (n_66), .B (n_78), .Y (n_11));
  AND2X1 g898__1705(.A (n_57), .B (n_78), .Y (n_10));
  AND2X1 g899__5122(.A (n_58), .B (n_78), .Y (n_9));
  AND2X1 g900__8246(.A (n_59), .B (n_78), .Y (n_8));
  AND2X1 g901__7098(.A (n_60), .B (n_78), .Y (n_7));
  AND2X1 g902__6131(.A (n_61), .B (n_78), .Y (n_6));
  AND2X1 g903__1881(.A (n_62), .B (n_78), .Y (n_5));
  AND2X1 g904__5115(.A (n_63), .B (n_78), .Y (n_4));
  AND2X1 g905__7482(.A (n_64), .B (n_78), .Y (n_3));
  AND2X1 g906__4733(.A (n_65), .B (n_78), .Y (n_2));
  AND2X1 g907__6161(.A (n_68), .B (n_78), .Y (n_1));
  INVX1 g908(.A (n_78), .Y (n_0));
  XNOR2X1 dec_sub_41_18_g780__9315(.A (timer[31]), .B
       (dec_sub_41_18_n_306), .Y (n_77));
  OAI2BB1X1 dec_sub_41_18_g781__9945(.A0N (timer[30]), .A1N
       (dec_sub_41_18_n_311), .B0 (dec_sub_41_18_n_306), .Y (n_76));
  OR2X1 dec_sub_41_18_g782__2883(.A (timer[30]), .B
       (dec_sub_41_18_n_311), .Y (dec_sub_41_18_n_306));
  OAI2BB1X1 dec_sub_41_18_g783__2346(.A0N (timer[29]), .A1N
       (dec_sub_41_18_n_316), .B0 (dec_sub_41_18_n_311), .Y (n_75));
  OR2X1 dec_sub_41_18_g784__1666(.A (timer[29]), .B
       (dec_sub_41_18_n_316), .Y (dec_sub_41_18_n_311));
  OAI2BB1X1 dec_sub_41_18_g785__7410(.A0N (timer[28]), .A1N
       (dec_sub_41_18_n_321), .B0 (dec_sub_41_18_n_316), .Y (n_74));
  OR2X1 dec_sub_41_18_g786__6417(.A (timer[28]), .B
       (dec_sub_41_18_n_321), .Y (dec_sub_41_18_n_316));
  OAI2BB1X1 dec_sub_41_18_g787__5477(.A0N (timer[27]), .A1N
       (dec_sub_41_18_n_326), .B0 (dec_sub_41_18_n_321), .Y (n_73));
  OR2X1 dec_sub_41_18_g788__2398(.A (timer[27]), .B
       (dec_sub_41_18_n_326), .Y (dec_sub_41_18_n_321));
  OAI2BB1X1 dec_sub_41_18_g789__5107(.A0N (timer[26]), .A1N
       (dec_sub_41_18_n_331), .B0 (dec_sub_41_18_n_326), .Y (n_72));
  OR2X1 dec_sub_41_18_g790__6260(.A (timer[26]), .B
       (dec_sub_41_18_n_331), .Y (dec_sub_41_18_n_326));
  OAI2BB1X1 dec_sub_41_18_g791__4319(.A0N (timer[25]), .A1N
       (dec_sub_41_18_n_336), .B0 (dec_sub_41_18_n_331), .Y (n_71));
  OR2X1 dec_sub_41_18_g792__8428(.A (timer[25]), .B
       (dec_sub_41_18_n_336), .Y (dec_sub_41_18_n_331));
  OAI2BB1X1 dec_sub_41_18_g793__5526(.A0N (timer[24]), .A1N
       (dec_sub_41_18_n_341), .B0 (dec_sub_41_18_n_336), .Y (n_70));
  OR2X1 dec_sub_41_18_g794__6783(.A (timer[24]), .B
       (dec_sub_41_18_n_341), .Y (dec_sub_41_18_n_336));
  OAI2BB1X1 dec_sub_41_18_g795__3680(.A0N (timer[23]), .A1N
       (dec_sub_41_18_n_346), .B0 (dec_sub_41_18_n_341), .Y (n_69));
  OR2X1 dec_sub_41_18_g796__1617(.A (timer[23]), .B
       (dec_sub_41_18_n_346), .Y (dec_sub_41_18_n_341));
  OAI2BB1X1 dec_sub_41_18_g797__2802(.A0N (timer[22]), .A1N
       (dec_sub_41_18_n_351), .B0 (dec_sub_41_18_n_346), .Y (n_68));
  OR2X1 dec_sub_41_18_g798__1705(.A (timer[22]), .B
       (dec_sub_41_18_n_351), .Y (dec_sub_41_18_n_346));
  OAI2BB1X1 dec_sub_41_18_g799__5122(.A0N (timer[21]), .A1N
       (dec_sub_41_18_n_356), .B0 (dec_sub_41_18_n_351), .Y (n_67));
  OR2X1 dec_sub_41_18_g800__8246(.A (timer[21]), .B
       (dec_sub_41_18_n_356), .Y (dec_sub_41_18_n_351));
  OAI2BB1X1 dec_sub_41_18_g801__7098(.A0N (timer[20]), .A1N
       (dec_sub_41_18_n_361), .B0 (dec_sub_41_18_n_356), .Y (n_66));
  OR2X1 dec_sub_41_18_g802__6131(.A (timer[20]), .B
       (dec_sub_41_18_n_361), .Y (dec_sub_41_18_n_356));
  OAI2BB1X1 dec_sub_41_18_g803__1881(.A0N (timer[19]), .A1N
       (dec_sub_41_18_n_366), .B0 (dec_sub_41_18_n_361), .Y (n_65));
  OR2X1 dec_sub_41_18_g804__5115(.A (timer[19]), .B
       (dec_sub_41_18_n_366), .Y (dec_sub_41_18_n_361));
  OAI2BB1X1 dec_sub_41_18_g805__7482(.A0N (timer[18]), .A1N
       (dec_sub_41_18_n_371), .B0 (dec_sub_41_18_n_366), .Y (n_64));
  OR2X1 dec_sub_41_18_g806__4733(.A (timer[18]), .B
       (dec_sub_41_18_n_371), .Y (dec_sub_41_18_n_366));
  OAI2BB1X1 dec_sub_41_18_g807__6161(.A0N (timer[17]), .A1N
       (dec_sub_41_18_n_376), .B0 (dec_sub_41_18_n_371), .Y (n_63));
  OR2X1 dec_sub_41_18_g808__9315(.A (timer[17]), .B
       (dec_sub_41_18_n_376), .Y (dec_sub_41_18_n_371));
  OAI2BB1X1 dec_sub_41_18_g809__9945(.A0N (timer[16]), .A1N
       (dec_sub_41_18_n_381), .B0 (dec_sub_41_18_n_376), .Y (n_62));
  OR2X1 dec_sub_41_18_g810__2883(.A (timer[16]), .B
       (dec_sub_41_18_n_381), .Y (dec_sub_41_18_n_376));
  OAI2BB1X1 dec_sub_41_18_g811__2346(.A0N (timer[15]), .A1N
       (dec_sub_41_18_n_386), .B0 (dec_sub_41_18_n_381), .Y (n_61));
  OR2X1 dec_sub_41_18_g812__1666(.A (timer[15]), .B
       (dec_sub_41_18_n_386), .Y (dec_sub_41_18_n_381));
  OAI2BB1X1 dec_sub_41_18_g813__7410(.A0N (timer[14]), .A1N
       (dec_sub_41_18_n_391), .B0 (dec_sub_41_18_n_386), .Y (n_60));
  OR2X1 dec_sub_41_18_g814__6417(.A (timer[14]), .B
       (dec_sub_41_18_n_391), .Y (dec_sub_41_18_n_386));
  OAI2BB1X1 dec_sub_41_18_g815__5477(.A0N (timer[13]), .A1N
       (dec_sub_41_18_n_396), .B0 (dec_sub_41_18_n_391), .Y (n_59));
  OR2X1 dec_sub_41_18_g816__2398(.A (timer[13]), .B
       (dec_sub_41_18_n_396), .Y (dec_sub_41_18_n_391));
  OAI2BB1X1 dec_sub_41_18_g817__5107(.A0N (timer[12]), .A1N
       (dec_sub_41_18_n_401), .B0 (dec_sub_41_18_n_396), .Y (n_58));
  OR2X1 dec_sub_41_18_g818__6260(.A (timer[12]), .B
       (dec_sub_41_18_n_401), .Y (dec_sub_41_18_n_396));
  OAI2BB1X1 dec_sub_41_18_g819__4319(.A0N (timer[11]), .A1N
       (dec_sub_41_18_n_406), .B0 (dec_sub_41_18_n_401), .Y (n_57));
  OR2X1 dec_sub_41_18_g820__8428(.A (timer[11]), .B
       (dec_sub_41_18_n_406), .Y (dec_sub_41_18_n_401));
  OAI2BB1X1 dec_sub_41_18_g821__5526(.A0N (timer[10]), .A1N
       (dec_sub_41_18_n_411), .B0 (dec_sub_41_18_n_406), .Y (n_56));
  OR2X1 dec_sub_41_18_g822__6783(.A (timer[10]), .B
       (dec_sub_41_18_n_411), .Y (dec_sub_41_18_n_406));
  OAI2BB1X1 dec_sub_41_18_g823__3680(.A0N (timer[9]), .A1N
       (dec_sub_41_18_n_416), .B0 (dec_sub_41_18_n_411), .Y (n_55));
  OR2X1 dec_sub_41_18_g824__1617(.A (timer[9]), .B
       (dec_sub_41_18_n_416), .Y (dec_sub_41_18_n_411));
  OAI2BB1X1 dec_sub_41_18_g825__2802(.A0N (timer[8]), .A1N
       (dec_sub_41_18_n_421), .B0 (dec_sub_41_18_n_416), .Y (n_54));
  OR2X1 dec_sub_41_18_g826__1705(.A (timer[8]), .B
       (dec_sub_41_18_n_421), .Y (dec_sub_41_18_n_416));
  OAI2BB1X1 dec_sub_41_18_g827__5122(.A0N (timer[7]), .A1N
       (dec_sub_41_18_n_426), .B0 (dec_sub_41_18_n_421), .Y (n_53));
  OR2X1 dec_sub_41_18_g828__8246(.A (timer[7]), .B
       (dec_sub_41_18_n_426), .Y (dec_sub_41_18_n_421));
  OAI2BB1X1 dec_sub_41_18_g829__7098(.A0N (timer[6]), .A1N
       (dec_sub_41_18_n_431), .B0 (dec_sub_41_18_n_426), .Y (n_52));
  OR2X1 dec_sub_41_18_g830__6131(.A (timer[6]), .B
       (dec_sub_41_18_n_431), .Y (dec_sub_41_18_n_426));
  OAI2BB1X1 dec_sub_41_18_g831__1881(.A0N (timer[5]), .A1N
       (dec_sub_41_18_n_436), .B0 (dec_sub_41_18_n_431), .Y (n_51));
  OR2X1 dec_sub_41_18_g832__5115(.A (timer[5]), .B
       (dec_sub_41_18_n_436), .Y (dec_sub_41_18_n_431));
  OAI2BB1X1 dec_sub_41_18_g833__7482(.A0N (timer[4]), .A1N
       (dec_sub_41_18_n_441), .B0 (dec_sub_41_18_n_436), .Y (n_50));
  OR2X1 dec_sub_41_18_g834__4733(.A (timer[4]), .B
       (dec_sub_41_18_n_441), .Y (dec_sub_41_18_n_436));
  OAI2BB1X1 dec_sub_41_18_g835__6161(.A0N (timer[3]), .A1N
       (dec_sub_41_18_n_446), .B0 (dec_sub_41_18_n_441), .Y (n_49));
  OR2X1 dec_sub_41_18_g836__9315(.A (timer[3]), .B
       (dec_sub_41_18_n_446), .Y (dec_sub_41_18_n_441));
  OAI2BB1X1 dec_sub_41_18_g837__9945(.A0N (timer[2]), .A1N
       (dec_sub_41_18_n_451), .B0 (dec_sub_41_18_n_446), .Y (n_48));
  OR2X1 dec_sub_41_18_g838__2883(.A (timer[2]), .B
       (dec_sub_41_18_n_451), .Y (dec_sub_41_18_n_446));
  OAI2BB1X1 dec_sub_41_18_g839__2346(.A0N (timer[0]), .A1N (timer[1]),
       .B0 (dec_sub_41_18_n_451), .Y (n_20));
  OR2X1 dec_sub_41_18_g840__1666(.A (timer[0]), .B (timer[1]), .Y
       (dec_sub_41_18_n_451));
  DFFRX1 \state_reg[1] (.RN (rst), .CK (rc_gclk), .D (n_35), .Q
       (NS[1]), .QN (EW[1]));
endmodule

